version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - neuro-inc/mlops
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
