kind: live
title: mlops-mlflow-model-deploy

volumes:
  modules:
    remote: storage:${{ project.id }}/modules
    mount: /project/modules
    local: modules
  triton_model_repo:
    remote: storage:${{ project.id }}/triton_model_repo
    mount: /tmp/project/triton_model_repo

images:
  app:
    ref: image:/$[[ project.owner ]]/$[[ flow.project_id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
  mlflow_server:
    ref: image:/$[[ project.owner ]]/$[[ flow.project_id ]]/mlflow-server:v2
    dockerfile: $[[ flow.workspace ]]/mlflow-server.Dockerfile
    context: $[[ flow.workspace ]]/


jobs:
  app:
    image: $[[ images.app.ref ]]
    volumes:
      - ${{ volumes.modules.ref_rw }}
      - ${{ volumes.triton_model_repo.ref_rw }}
    env:
      MLFLOW_TRACKING_URI: https://mlops-pytorch-mlflow-trito-mlflow-server--yevheniisemendiak.jobs.green-a4000-1.org.neu.ro
      MLFLOW_TRACKING_TOKEN: secret:in-job-deployment-auth-token
      TRITON_MODEL_REPO: ${{ volumes.triton_model_repo.mount }}
    bash: |
      streamlit run ${{ volumes.modules.mount }}/streamlit-app.py

  webdav:
    action: gh:neuro-actions/webdav_server@v1.0.0
    args:
      volume_remote: ${{ volumes.triton_model_repo.remote }}
      job_lifespan: 30d