## Check our full reference documentation at https://neu-ro.gitbook.io/neuro-flow/reference/project-configuration-syntax
id: mlops_mlflow_model_deploy
## Could be referenced as $[[ project.id ]] or $[[ flow.project_id ]] contexts.
## Default value: name of the folder containing `.neuro`
owner: yevheniisemendiak
## Optional platform user that owns the project, referenced via $[[ project.owner ]]
role: yevheniisemendiak/projects/mlops_mlflow_model_deploy
## Optional platform role which can be used to share the project
##   with other platform users via `neuro acl grant <role> <user> {read|write|manage}`
